### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [31]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [36]:
help(np.array)
dir(np.array)
dir(car)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [13]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)
#"car" is an object; "mpg" is a float; "horsepower" is a float; "origin" is an object

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#It's called "creating an alias." It shortens the phrase "numpy" to make subsequent coding easier to type and to read.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [54]:
#Each array has one dimension because they are all just individual columns.
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim)
print(weight.ndim)
print(acceleration.ndim)
print(model.ndim)
print(origin.ndim)

1
1
1
1
1
1
1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [14]:
np_mpg * 12
np_mpg / 3
np_mpg ** 4
np.sqrt(np_mpg)

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [24]:
print('HP sum: ',np.sum(horsepower))
print('HP min: ',np.min(horsepower))
print('HP max: ',np.max(horsepower))
print('HP median: ',np.median(horsepower))
import scipy
from scipy.stats import mode
scipy.stats.mode(horsepower)
hp_mode = scipy.stats.mode(horsepower)
print('HP mode: ',hp_mode[0])

HP sum:  42033.0
HP min:  0.0
HP max:  230.0
HP median:  93.5
HP mode:  [150.]


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [56]:
np_acceleration = np.reshape(acceleration,(-1, 2))
np_acceleration.shape
np_accel_five = np_acceleration[:5,0]
print(np_accel_five)
#Based on the panda table, it looks like these are not the correct first five values...
np_accel_other = np_acceleration[4:,0]
print(np_accel_other)
#... and I'm not sure this is enough values to be everything but 1-5.

[12.  11.  10.5  9.  10. ]
[10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5 17.5 15.  15.  18.5
 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.  14.  19.5 19.  19.
 15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.  18.  18.  17.  15.
 13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.  13.  15.  19.5 13.5
 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.  17.  16.5 14.5 16.
 16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5 18.5 19.  13.5 16.
 16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.  13.9 15.4 17.6 22.2
 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.  14.8 15.5 12.5 13.7
 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5 14.4 18.6 15.5 12.8
 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7 14.9 13.6 15.8 16.6
 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8 13.2 19.2 16.  12.9
 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9 13.8 18.  11.4 15.1
 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4 14.8 20.4 19.6 13.8
 19.  16.6 18.6 16.2 18.  20.5 18.2 14.7 14.5 16.9 15.

8. Show how to select the number `99` in the array below. 

In [33]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [34]:
only_99 = select_99[1,2]
print(only_99)

99


9. Select the last element in each subarray (do this with one operation.)

In [38]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [39]:
select_last = select_more[:3,2]
print(select_last)

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [26]:
np.log(mpg)

<ipython-input-26-f03654513e4b>:1: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. Use your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [27]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [52]:
x = np.array([[1],[2],[3]])
x.shape
#Output: (3,1)
x.ndim
#Output: 2
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
y.shape
#Output: (2, 3, 1)
y.ndim
#Output: 3
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
z = np.expand_dims(z, axis=0)
z = np.repeat(z, 4, axis=0)
z.shape
#Output: (4, 3, 2, 3)
z.ndim
#Output: 4

4

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [53]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [57]:
origin_us = (origin=='US')
car[origin_us]

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

2. Transpose the following array. 

In [71]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


<built-in method transpose of numpy.ndarray object at 0x7f81e654d8a0>


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [63]:
origin_eur = (origin=='Europe')
hp_eur = horsepower[origin_eur]
print(np.mean(hp_eur))


78.78082191780823


5. On average are Japanese cars more fuel efficient than US cars? 

In [67]:
origin_US = (origin=='US')
mpg_US = mpg[origin_US]
print('Average US mpg:',np.mean(mpg_US))
origin_Japan = (origin=='Japan')
mpg_Japan = mpg[origin_Japan]
print('Average Japan mpg:',np.mean(mpg_Japan))
#Yes, the Japanese cars are much more fuel efficient than the US cars!

Average US mpg: 19.688188976377955
Average Japan mpg: 30.450632911392404


6. What is the correlation coefficient of `mpg` and `weight`?

In [70]:
np.corrcoef(mpg, weight)
#The correlation coefficient is -0.78750994

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 